touch: touch.exe

clean:
	del touch.exe touch.obj touch.res

touch.exe: touch.obj touch.res
	link /NOLOGO touch.obj touch.res

touch.obj: touch.cpp
	cl /c /nologo /O1 touch.cpp

touch.res: touch.rc touch.ico
	rc touch.rc
